Small improvements to nicer CI errors
Brezak/bevy pull request #2
Opened 2024-05-08 02:30 UTC by BD103

This refactors a few bits of code, but does not change any logic. :)

2024-05-08 09:12 UTC, Brezak requested changes

2024-05-08 09:12 UTC, Brezak commented on tools/ci/src/commands/mod.rs
> +    })
Did you tests this? I'm pretty sure this deadlocks.
1. Cargo writes a bunch of data to it's stdout.
2. The pipe buffer gets filled. All subsequent writes block.
3. We wait for the process to finish.
4. Process is stuck waiting for stdout write to finish.

The old behavior would be:
1. Cargo writes a bunch of data to it's stdout.
2. We consume this data in `from_cargo_output`.
2.a If parsing the data fails we drop the child stdout handle closing it. All subsequent writes will fail.
3. We wait for the child to finish.

2024-05-08 09:12 UTC, Brezak commented on tools/ci/src/commands/mod.rs
>          .stdout(Stdio::piped())
We need to read what cargo outputs while it's running.
The childs stdio is configured as such:
- `stdin` is inherited from ours. Any reads cargo attempts will be read from our `stdin`.
- `stderr` is inherited from ours. Any writes will show up in console. Due to how cargo determines if output should be colored we should also get color on this output.
- `stdout` is piped directly to us. Any writes to it go directly to a [handle](https://doc.rust-lang.org/std/process/struct.ChildStdout.html) we can [read](https://doc.rust-lang.org/std/io/trait.Read.html). We handle this data in `JsonCommandOutput::from_cargo_output`

2024-05-09 00:07 UTC, BD103 commented on tools/ci/src/commands/mod.rs
>          .stdout(Stdio::piped())
Thank you, that makes a lot more sense! (I misread `Stdio` as `Stdin`, and was wondering why we were connecting `stdout` and `stdin` together 😅)

2024-05-09 00:11 UTC, BD103 commented on tools/ci/src/commands/mod.rs
> +    })
> Did you tests this? I'm pretty sure this deadlocks.

I didn't test this (probably should have!), and it definitely deadlocks. Let me revert that!

2024-05-09 09:01 UTC, merged